# Generated by Django 5.2.17 on 2026-08-23 10:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0003_aigeneration'),
        ('classes', '0001_initial'),
        ('library', '0002_alter_resource_language'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(max_length=150)),
                ('subtopic', models.CharField(blank=True, max_length=150)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_STRUCTURED', 'Short structural'), ('STRUCTURED', 'Structured'), ('GROUPED_STRUCTURED', 'Grouped structural'), ('ESSAY', 'Essay'), ('CALCULATION', 'Calculation'), ('PRACTICAL', 'Practical'), ('OTHER', 'Other')], default='SHORT_STRUCTURED', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('marks', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('bloom_level', models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('COMPREHENSION', 'Comprehension'), ('APPLICATION', 'Application'), ('ANALYSIS', 'Analysis'), ('SYNTHESIS', 'Synthesis'), ('EVALUATION', 'Evaluation')], default='KNOWLEDGE', max_length=15)),
                ('body', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('marking_scheme', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='ai.aigeneration')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='library.bookchapter')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='schools.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='classes.schoolclass')),
                ('source_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='library.resource')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='subjects.subject')),
            ],
            options={
                'ordering': ['school__name', 'subject__name', 'topic', '-created_at'],
                'indexes': [models.Index(fields=['school', 'approval_status'], name='question_ba_school__45b30b_idx'), models.Index(fields=['school', 'subject', 'topic'], name='question_ba_school__555bfa_idx'), models.Index(fields=['school', 'question_type', 'difficulty'], name='question_ba_school__fed27d_idx')],
            },
        ),
    ]
