# Generated by Django 5.2.17 on 2026-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=10),
        ),
    ]
