# Generated by Django 5.2.17 on 2026-08-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='step',
            field=models.CharField(choices=[('EXTRACT', 'Extract text'), ('CHUNK', 'Chunk text'), ('EMBED', 'Embed chunks')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=120)),
                ('dimensions', models.PositiveSmallIntegerField()),
                ('vector', models.JSONField()),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='documents.documentchunk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
