# Generated by Django 5.2.17 on 2026-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_processingjob_step_chunkembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedpage',
            name='needs_ocr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractedpage',
            name='ocr_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedpage',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
