# Generated by Django 5.2.17 on 2026-08-23 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('question_bank', '0001_initial'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('SELF_QUIZ', 'Self quiz'), ('PUBLISHED_EXAM', 'Published exam')], default='SELF_QUIZ', max_length=16)),
                ('topic_filter', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=12)),
                ('possible_marks', models.PositiveIntegerField(default=0)),
                ('earned_marks', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_attempts', to='schools.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='subjects.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('given_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('awarded_marks', models.PositiveSmallIntegerField(default=0)),
                ('self_marked', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_responses', to='question_bank.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.practiceattempt')),
            ],
            options={
                'ordering': ['attempt', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['student', 'status'], name='learning_pr_student_16d155_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['school', 'created_at'], name='learning_pr_school__e7177d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_question_per_attempt'),
        ),
    ]
