# Generated by Django 5.2.17 on 2026-08-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='schools.school')),
            ],
            options={
                'ordering': ['school__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'), models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school')],
            },
        ),
    ]
