# Generated by Django 5.2.17 on 2026-08-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('EMBED', 'Embedding'), ('GENERATE', 'Generation')], max_length=12)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('input_items', models.PositiveIntegerField(default=1)),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'model', 'kind'], name='ai_aireques_provide_51a004_idx')],
            },
        ),
    ]
