# Generated by Django 5.2.17 on 2026-08-23 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope', models.CharField(choices=[('GENERAL', 'General AI'), ('LIBRARY', 'Whole library'), ('SUBJECT', 'Subject'), ('CLASS', 'Class/form'), ('BOOK', 'Book'), ('CHAPTER', 'Chapter')], default='LIBRARY', max_length=12)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('cited_chunk_ids', models.JSONField(blank=True, default=list)),
                ('retrieved_count', models.PositiveSmallIntegerField(default=0)),
                ('used_provider', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_interactions', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aiintera_user_id_327664_idx'), models.Index(fields=['school', 'created_at'], name='ai_aiintera_school__1ba408_idx')],
            },
        ),
    ]
