# Generated by Django 5.2.17 on 2026-08-23 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiinteraction'),
        ('library', '0002_alter_resource_language'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('SUMMARY', 'Summary'), ('REVISION_NOTES', 'Revision notes'), ('DEFINITIONS_FORMULAE', 'Definitions and formulae'), ('PRACTICE_QUESTIONS', 'Practice questions')], max_length=24)),
                ('scope', models.CharField(choices=[('GENERAL', 'General AI'), ('LIBRARY', 'Whole library'), ('SUBJECT', 'Subject'), ('CLASS', 'Class/form'), ('BOOK', 'Book'), ('CHAPTER', 'Chapter')], max_length=12)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('cited_chunk_ids', models.JSONField(blank=True, default=list)),
                ('retrieved_count', models.PositiveSmallIntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('used_provider', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_generations', to='schools.school')),
                ('source_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to='library.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aigenera_user_id_252fd0_idx'), models.Index(fields=['school', 'kind'], name='ai_aigenera_school__a7cd88_idx')],
            },
        ),
    ]
