# Generated by Django 5.2.17 on 2026-08-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aigeneration'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_request_logs', to='schools.school'),
        ),
    ]
