# Generated by Django 5.2.17 on 2026-08-23 10:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('question_bank', '0001_initial'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('total_marks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (assembling)'), ('READY_FOR_REVIEW', 'Ready for review'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='schools.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classes.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='subjects.subject')),
            ],
            options={
                'ordering': ['school__name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('marks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='examinations.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_slots', to='question_bank.question')),
            ],
            options={
                'ordering': ['exam', 'position'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'question'), name='unique_question_per_exam')],
            },
        ),
    ]
